name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    outputs:
      need-build: ${{ steps.check.outputs.need-build }}
      latest-version: ${{ steps.check.outputs.latest-version }}
    steps:
      - run: ls -l
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: generate.yml
          workflow_conclusion: success
      - run: ls -l
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: '*.zip/*.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
